apiVersion: v1
kind: ConfigMap
metadata:
  name: flyway-sql-scripts
data:
  V1__Initial_schema.sql: |
    CREATE TABLE IF NOT EXISTS sample_table (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(255) NOT NULL
    );
  V2__Seed_data.sql: |
    INSERT INTO sample_table (name) VALUES ('Sample Name 1'), ('Sample Name 2');
