---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app
          image: afakharany/python-db-client:1.0
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_HOST
              value: mysql-sample.default.svc.cluster.local
            - name: MYSQL_USER
              value: dbuser
            - name: MYSQL_PASSWORD
              value: dbpassword
            - name: MYSQL_DATABASE
              value: my_database