apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-redis-app
  labels:
    app: flask-redis-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-redis-app
  template:
    metadata:
      labels:
        app: flask-redis-app
    spec:
      containers:
      - name: flask-redis-app
        image: afakharany/python-redis:1.0
        ports:
        - containerPort: 8000

