apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-db-client
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/abohmeed/argocd-resourcehooks-lab.git'
    targetRevision: HEAD
    path: 'presynchook/db-app'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
