apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-sample
  namespace: argocd
spec:
  project: default
  source:
    chart: mysql
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 9.23.0
    helm:
      releaseName: mysql-sample
      values: |
        auth:
          username: dbuser
          password: dbpassword
          name: my_database
          createDatabase: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated: {}